# Generated by Django 3.2.3 on 2021-08-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0006_message_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file_name',
            field=models.CharField(default=None, max_length=1000000, null=True),
        ),
    ]
