# Generated by Django 3.2.3 on 2021-08-12 05:20

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0007_alter_message_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='uploaded_files/'),
        ),
    ]
